import json
import random

PREVIOUS_SEGMENTS = [
    "",
    "Hey guys welcome back to the channel",
    "So basically what happened was",
    "I was watching this video yesterday",
    "You won't believe what I found",
    "Before we start the video",
    "Let me explain this properly",
    "A lot of people don't know this",
    "This is actually very interesting",
    "I tried this for the first time",
    "At first I thought it was fake",
    "If you look closely here",
    "One thing I noticed was",
    "Back when I started doing this",
    "I honestly didn't expect this result",
    "The funny thing is",
    "After a few minutes",
    "Suddenly everything changed",
    "For those who are new here",
    "I have been testing this recently",
    "The reason why this matters is",
    "Most people usually ignore this part",
    "And then something crazy happened",
    "Right before the video ended",
    "This reminds me of another experiment",
    "A subscriber actually suggested this",
    "I saw a comment about this earlier",
    "Just imagine this situation",
    "A few days ago",
    "When I first heard about this",
    "The main problem here is",
    "People keep asking me this question",
    "So today we are going to test",
    "I don't think anyone expected that",
    "At this point I was confused",
    "There is one important detail",
    "Some of you may already know",
    "I decided to give this a try",
    "",
    "This part is extremely important",
    "The best thing about this is",
    "Nobody talks about this enough",
    "If this actually works",
    "The results were surprisingly good",
    "After watching this multiple times",
    "I think this could be useful",
    "This might sound weird but",
    "And that's when I realized",
    "The camera didn't capture everything",
    "For some reason",
    "",
    "I kept thinking about this later",
    "In today's video",
    "A lot of viewers requested this",
    "This was completely unexpected",
    "I don't usually make videos like this",
    "Right in the middle of recording",
    "At the end of the day",
    "This could change everything",
    "I wasn't ready for this moment",
    "While editing the footage",
    "This is probably the strangest thing",
]

CURRENT_SEGMENTS = [
    "the drone suddenly lost signal",
    "someone started knocking on the door",
    "the camera quality became much clearer",
    "I noticed a strange sound in the background",
    "the experiment finally started working",
    "the lights turned off automatically",
    "the game began to lag badly",
    "a random dog appeared out of nowhere",
    "the laptop overheated within minutes",
    "everyone in the chat was confused",
    "the robot responded unexpectedly",
    "the internet connection completely dropped",
    "the prediction model failed again",
    "the battery percentage started decreasing fast",
    "the teacher explained the concept differently",
    "the car stopped in the middle of the road",
    "the screen froze for a few seconds",
    "the microphone captured a weird noise",
    "the AI generated something unusual",
    "the video suddenly went viral",
    "the code worked on the first try",
    "the results looked surprisingly accurate",
    "the phone started vibrating continuously",
    "the system detected multiple objects",
    "the audience began laughing loudly",
    "the weather changed within minutes",
    "the tracking system lost the target",
    "the server crashed during the demo",
    "the audio became completely distorted",
    "the application responded much faster",
    "the player missed an easy shot",
    "the map updated in real time",
    "the software installation failed halfway",
    "the machine started making loud noises",
    "the signal became weaker underground",
    "the image processing took longer than expected",
    "the animation looked very realistic",
    "the drone camera detected movement",
    "the person suddenly disappeared from the frame",
    "the entire setup stopped responding",
    "the crowd started cheering instantly",
    "the output looked much cleaner",
    "the test results shocked everyone",
    "the package arrived earlier than expected",
    "the algorithm improved the accuracy",
    "the lights began flickering rapidly",
    "the security alarm turned on",
    "the background music became louder",
    "the thermal camera detected heat signatures",
    "the engine started overheating",
    "the stream disconnected unexpectedly",
    "the character moved in the wrong direction",
    "the object detection system failed",
    "the device restarted automatically",
    "the AI assistant answered correctly",
    "the camera lens became blurry",
    "the program consumed too much memory",
    "the GPS coordinates updated incorrectly",
    "the sound effect played twice",
    "the experiment produced unexpected results"
]

FUTURE_SEGMENTS = [
    "",
    "and nobody knew what was happening",
    "before the video suddenly ended",
    "which honestly surprised everyone",
    "and I still can't explain why",
    "while everyone was watching live",
    "and the results became even stranger",
    "before things got completely out of control",
    "which made the situation even worse",
    "and that changed everything instantly",
    "",
    "before we could stop the recording",
    "and people in the comments noticed it too",
    "which was actually a good sign",
    "before the system crashed again",
    "and it happened faster than expected",
    "which made the experiment successful",
    "before anyone realized the mistake",
    "and the whole chat started reacting",
    "which nobody was prepared for",
    "before the lights turned back on",
    "and the audio became distorted afterwards",
    "",
    "which caused a lot of confusion online",
    "before the connection was restored",
    "and it kept getting more intense",
    "which made me laugh for a minute",
    "before the drone lost power completely",
    "and everything started working perfectly",
    "which looked really cinematic",
    "before the battery finally died",
    "and the camera captured the entire moment",
    "which turned into a huge problem later",
    "before the software restarted itself",
    "and nobody expected that outcome",
    "which made the footage look fake",
    "",
    "before we moved to the next test",
    "and the background noise disappeared",
    "which actually improved the quality",
    "before someone interrupted the recording",
    "and it all happened in real time",
    "which made the audience panic",
    "before the stream disconnected",
    "and the AI kept repeating the same thing",
    "which became a meme later",
    "before the sensors stopped responding",
    "and everyone started asking questions",
    "",
    "which completely changed my opinion",
    "before the internet connection dropped again",
    "and the device overheated immediately",
    "which looked much better after editing",
    "before the final results appeared on screen",
    "and the tracking system recovered automatically",
    "which made the test more accurate",
    "before the robot stopped moving",
    "and the entire room went silent",
    "which turned out to be a misunderstanding",
    "before the application closed unexpectedly",
    "and people started clipping the moment",
    "which became the highlight of the stream",
    "before everything returned to normal",
    "and the footage was uploaded later"
]


with open("test_json.json","w") as f:
    data = {}
    for i in range(100):
        segment_data = {}
        part1 = random.randint(0,len(PREVIOUS_SEGMENTS)-1)
        part2 = random.randint(0,len(CURRENT_SEGMENTS)-1)
        part3 = random.randint(0,len(FUTURE_SEGMENTS)-1)
        segment_data = {
            "PREVIOUS_SEGMENT" : PREVIOUS_SEGMENTS[part1],
            "CURRENT_SEGMENT" : CURRENT_SEGMENTS[part2],
            "FUTURE_SEGMENT" : FUTURE_SEGMENTS[part3]
        }
        data[f"seg_{i}"] = (segment_data)

    data_json = json.dumps(data,indent=4)
    f.write(data_json)